### ISSUE TITLE
[FEATURE] Update script or some kind of tutorial

### ISSUE THREAD

**Issue by deviousbehaviour** [AlexProgrammerDE/balena-minecraft-server#37]
I am currently struggling with very little linux knowledge and the desire to update from my previous MC server (1.15.x) to the most recent one (1.16.x) and I don't see any documentation on how to do this.

I would love a tutorial or even a script to make this process seamless from putty or balena.

I absolutely love love love this software, so far it's been the most stable and best server ever!  Thank you guys so much!

Also:  I am a noob, so if I'm missing something obvious, please treat me like a noob and help me learn and get better! ^_^

**Comment by AlexProgrammerDE** [comment]
@deviousbehaviour oof sorry for the late answee. Just set the `ENABLE_UPDATE` variable with the 1.16 repository update on the PI and it will overwrite the old file.

**Comment by chazzytho** [comment]
@deviousbehaviour I don't know if this will help, but since the issue's still open, I thought I'd pitch in. I finally got around to updating my minecraft server to 1.16.2 after putting it off for many months, so here are the steps I went through (I did this from my macbook). It's basically the steps [here](https://www.balena.io/blog/how-to-create-a-minecraft-server-for-the-pi-4-with-balena/) from the "Deploy the project code" section:

1. download the zip folder from [github ](https://github.com/AlexProgrammerDE/balena-minecraft-server) and unzip

2. open terminal and log into balena with `balena login`

3. navigate into the unzipped folder and push with `balena push (Application name on balena cloud)`. In my case, it was `balena push Minecraft_Server` (you can check this by logging into balenaCloud).

4. once that's done, log into balenaCloud on your browser, you should see that the application is updating.

5. set a new environment variable `ENABLE_UPDATE` and set it to `true`

6. Restart your minecraft server via balenacloud. This step takes a while, so be patient. I needed to repeat this step 2 times  because I was impatient and interrupted the update, causing some errors. Just keep an eye on the logs. Once that's done, the server should come back online on minecraft after a few minutes!

7. Delete the environment variable you created in balenaCloud, although I'm not sure how important this step is.

I hope this helps! At step 6. I interrupted the update, so I had to connect to it via SCP and delete the paper.jar file and restart the system, but I hope you won't have to do that. In order to reset your nether in case you've explored it a fair bit, just delete the world_nether folder via SCP and restart the server. Remember to transfer any important items back to the overworld before doing that though! I think I lost some wither skeleton skulls...
