### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by Clubeddie** [AlexProgrammerDE/balena-minecraft-server#62]
Don't know if I can ask the question here but I did not find another option. First of all great product. With your setup the server was up in no time.

I build it for my daughter, I have knowledge of raspberry pi's, see of minecraft. So I want a home server where see can play with friends. But I think what I want is not possible, but want to ask it anyway.

See has minecraft version 1.16.200 (updated a couple of minutes ago it was 1.16.101) on her iPad. But I cannot get it connect to the minecraft server, local and online (after port forwarding) not possible.
I tried the default port number 25565 as port number on the iPad and also port number 19132 from outside (found some info that some versions need this port).

But sadly no luck. Am I trying something to do which is not possible at all. So my question is, which versions/devices can connect to minecraft server? I thought I read that all devices working with minecraft on the raspberry but cannot find a solution. Hope you can help me. Feeling pretty stupid right now 😌

**Comment by EvilNick2** [comment]
If you did not know the computer version of Minecraft (Java Edition) and what is played on other devices such as phones, tablets and consoles use a different version of Minecraft called Bedrock Edition. So you problem would be you need to create a bedrock server and upload it to the Pi instead of what it comes preloaded with which is a Paper server and that is connected to with the  Java Edition of the game.
The Breakdown made a fantastic video explaining how to create a Bedrock server on his channel [here](https://www.youtube.com/watch?v=9dzcoJBH2zQ)

**Comment by Clubeddie** [comment]
Crap, i thougt it must have something to do with the versions. Thanks for the reply. Read some info. Bedrock is not an option for a raspberry pi because of the architecture. Raspberry Pi or PE edition are not available anymore. No i have to figure out what i am gonna do with this 7th Raspberry pi :-)

**Comment by AlexProgrammerDE** [comment]
@Clubeddie there is this project called geysermc: https://geysermc.org/
Its a project that opens a proxy to a java server. That allows bedrock players to join on a java server, what you currently have.
